### ISSUE TITLE
repository name has a typo and readme can be improved

### ISSUE THREAD

**Issue by gmvelencoso** [GabbsM/Programming-exercices-whit-Gerard#1]
repository name contains a typo and looks weird.

I suggest renaming it to "programming-exercises" or better "programming-workshop" (taller de programación).

You can rename the repo in the repo settings.

Also, readme could be improved by:

- putting the new name of the repository as header
- instead of saying Gerard, you could mention me with @gmvelencoso ;)
- adding some explanation of the project structure:
  - one directory per project (I'll create a PR regarding this) https://github.com/GabbsM/Programming-exercices-whit-Gerard/pull/2

extra tip: get familiar with [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax). Bullet lists, titles, sections, code blocks, etc will make your readme.md more interesting ;)

Cheers

**Comment by GabbsM** [comment]
repository changed
