### ISSUE TITLE
.idea is included in .gitignore but it has been pushed 

### ISSUE THREAD

**Issue by gmvelencoso** [GabbsM/Programming-exercices-whit-Gerard#3]
Let's remove the `.idea` directory. It's added to gitignore so it shouldn't be tracked, but it seems it has been pushed at the same time ;)

**Comment by gmvelencoso** [comment]
Maybe the problem is the filename 😅 
it should be `.gitignore`, not `.gitignore.txt` ;)

**Comment by GabbsM** [comment]
fixed issues. Thanks for your help!
